//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AxonAccessMVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class axonAccessEntities1 : DbContext
    {
        public axonAccessEntities1()
            : base("name=axonAccessEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Mae_Comuna> Mae_Comuna { get; set; }
        public virtual DbSet<Mae_Empresa> Mae_Empresa { get; set; }
        public virtual DbSet<Mae_Puerta> Mae_Puerta { get; set; }
        public virtual DbSet<Mae_Region> Mae_Region { get; set; }
        public virtual DbSet<Mae_Sucursal> Mae_Sucursal { get; set; }
        public virtual DbSet<Mae_Usuario> Mae_Usuario { get; set; }
        public virtual DbSet<Ref_DetalleAcceso> Ref_DetalleAcceso { get; set; }
        public virtual DbSet<Ref_Estado> Ref_Estado { get; set; }
        public virtual DbSet<Ref_Role> Ref_Role { get; set; }
        public virtual DbSet<Ref_UserAccess> Ref_UserAccess { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<USUARIO_AUD> USUARIO_AUD { get; set; }
        public virtual DbSet<Ref_Estamento> Ref_Estamento { get; set; }
        public virtual DbSet<Ref_accessTipo> Ref_accessTipo { get; set; }
        public virtual DbSet<Mae_Pais> Mae_Pais { get; set; }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int SP_INS_USUARIO_MASS(Nullable<int> iD_ROLE, Nullable<int> iD_ESTADO, Nullable<int> iD_COMUNA, Nullable<int> iD_EMPRESA, Nullable<int> rUT, string dV, string nOMBRE, string aPP_PATER, string aPP_MATER, string dIRECCION, Nullable<int> tELEFONO, string eMAIL, string pASS, string lATITUD, string lONGITUD, string cOD_PAIS)
        {
            var iD_ROLEParameter = iD_ROLE.HasValue ?
                new ObjectParameter("ID_ROLE", iD_ROLE) :
                new ObjectParameter("ID_ROLE", typeof(int));
    
            var iD_ESTADOParameter = iD_ESTADO.HasValue ?
                new ObjectParameter("ID_ESTADO", iD_ESTADO) :
                new ObjectParameter("ID_ESTADO", typeof(int));
    
            var iD_COMUNAParameter = iD_COMUNA.HasValue ?
                new ObjectParameter("ID_COMUNA", iD_COMUNA) :
                new ObjectParameter("ID_COMUNA", typeof(int));
    
            var iD_EMPRESAParameter = iD_EMPRESA.HasValue ?
                new ObjectParameter("ID_EMPRESA", iD_EMPRESA) :
                new ObjectParameter("ID_EMPRESA", typeof(int));
    
            var rUTParameter = rUT.HasValue ?
                new ObjectParameter("RUT", rUT) :
                new ObjectParameter("RUT", typeof(int));
    
            var dVParameter = dV != null ?
                new ObjectParameter("DV", dV) :
                new ObjectParameter("DV", typeof(string));
    
            var nOMBREParameter = nOMBRE != null ?
                new ObjectParameter("NOMBRE", nOMBRE) :
                new ObjectParameter("NOMBRE", typeof(string));
    
            var aPP_PATERParameter = aPP_PATER != null ?
                new ObjectParameter("APP_PATER", aPP_PATER) :
                new ObjectParameter("APP_PATER", typeof(string));
    
            var aPP_MATERParameter = aPP_MATER != null ?
                new ObjectParameter("APP_MATER", aPP_MATER) :
                new ObjectParameter("APP_MATER", typeof(string));
    
            var dIRECCIONParameter = dIRECCION != null ?
                new ObjectParameter("DIRECCION", dIRECCION) :
                new ObjectParameter("DIRECCION", typeof(string));
    
            var tELEFONOParameter = tELEFONO.HasValue ?
                new ObjectParameter("TELEFONO", tELEFONO) :
                new ObjectParameter("TELEFONO", typeof(int));
    
            var eMAILParameter = eMAIL != null ?
                new ObjectParameter("EMAIL", eMAIL) :
                new ObjectParameter("EMAIL", typeof(string));
    
            var pASSParameter = pASS != null ?
                new ObjectParameter("PASS", pASS) :
                new ObjectParameter("PASS", typeof(string));
    
            var lATITUDParameter = lATITUD != null ?
                new ObjectParameter("LATITUD", lATITUD) :
                new ObjectParameter("LATITUD", typeof(string));
    
            var lONGITUDParameter = lONGITUD != null ?
                new ObjectParameter("LONGITUD", lONGITUD) :
                new ObjectParameter("LONGITUD", typeof(string));
    
            var cOD_PAISParameter = cOD_PAIS != null ?
                new ObjectParameter("COD_PAIS", cOD_PAIS) :
                new ObjectParameter("COD_PAIS", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_INS_USUARIO_MASS", iD_ROLEParameter, iD_ESTADOParameter, iD_COMUNAParameter, iD_EMPRESAParameter, rUTParameter, dVParameter, nOMBREParameter, aPP_PATERParameter, aPP_MATERParameter, dIRECCIONParameter, tELEFONOParameter, eMAILParameter, pASSParameter, lATITUDParameter, lONGITUDParameter, cOD_PAISParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Sp_LoginUsuario(string mail, string pass)
        {
            var mailParameter = mail != null ?
                new ObjectParameter("mail", mail) :
                new ObjectParameter("mail", typeof(string));
    
            var passParameter = pass != null ?
                new ObjectParameter("Pass", pass) :
                new ObjectParameter("Pass", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Sp_LoginUsuario", mailParameter, passParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upd_user(Nullable<int> iD_USUARIO, Nullable<int> iD_ROLE, Nullable<int> iD_ESTADO, Nullable<int> iD_COMUNA, Nullable<int> iD_EMPRESA, Nullable<int> rUT, string dV, string nOMBRE, string aPP_PATER, string aPP_MATER, string dIRECCION, Nullable<int> tELEFONO, string eMAIL, string pASS, string lATITUD, string lONGITUD, string cOD_PAIS)
        {
            var iD_USUARIOParameter = iD_USUARIO.HasValue ?
                new ObjectParameter("ID_USUARIO", iD_USUARIO) :
                new ObjectParameter("ID_USUARIO", typeof(int));
    
            var iD_ROLEParameter = iD_ROLE.HasValue ?
                new ObjectParameter("ID_ROLE", iD_ROLE) :
                new ObjectParameter("ID_ROLE", typeof(int));
    
            var iD_ESTADOParameter = iD_ESTADO.HasValue ?
                new ObjectParameter("ID_ESTADO", iD_ESTADO) :
                new ObjectParameter("ID_ESTADO", typeof(int));
    
            var iD_COMUNAParameter = iD_COMUNA.HasValue ?
                new ObjectParameter("ID_COMUNA", iD_COMUNA) :
                new ObjectParameter("ID_COMUNA", typeof(int));
    
            var iD_EMPRESAParameter = iD_EMPRESA.HasValue ?
                new ObjectParameter("ID_EMPRESA", iD_EMPRESA) :
                new ObjectParameter("ID_EMPRESA", typeof(int));
    
            var rUTParameter = rUT.HasValue ?
                new ObjectParameter("RUT", rUT) :
                new ObjectParameter("RUT", typeof(int));
    
            var dVParameter = dV != null ?
                new ObjectParameter("DV", dV) :
                new ObjectParameter("DV", typeof(string));
    
            var nOMBREParameter = nOMBRE != null ?
                new ObjectParameter("NOMBRE", nOMBRE) :
                new ObjectParameter("NOMBRE", typeof(string));
    
            var aPP_PATERParameter = aPP_PATER != null ?
                new ObjectParameter("APP_PATER", aPP_PATER) :
                new ObjectParameter("APP_PATER", typeof(string));
    
            var aPP_MATERParameter = aPP_MATER != null ?
                new ObjectParameter("APP_MATER", aPP_MATER) :
                new ObjectParameter("APP_MATER", typeof(string));
    
            var dIRECCIONParameter = dIRECCION != null ?
                new ObjectParameter("DIRECCION", dIRECCION) :
                new ObjectParameter("DIRECCION", typeof(string));
    
            var tELEFONOParameter = tELEFONO.HasValue ?
                new ObjectParameter("TELEFONO", tELEFONO) :
                new ObjectParameter("TELEFONO", typeof(int));
    
            var eMAILParameter = eMAIL != null ?
                new ObjectParameter("EMAIL", eMAIL) :
                new ObjectParameter("EMAIL", typeof(string));
    
            var pASSParameter = pASS != null ?
                new ObjectParameter("PASS", pASS) :
                new ObjectParameter("PASS", typeof(string));
    
            var lATITUDParameter = lATITUD != null ?
                new ObjectParameter("LATITUD", lATITUD) :
                new ObjectParameter("LATITUD", typeof(string));
    
            var lONGITUDParameter = lONGITUD != null ?
                new ObjectParameter("LONGITUD", lONGITUD) :
                new ObjectParameter("LONGITUD", typeof(string));
    
            var cOD_PAISParameter = cOD_PAIS != null ?
                new ObjectParameter("COD_PAIS", cOD_PAIS) :
                new ObjectParameter("COD_PAIS", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upd_user", iD_USUARIOParameter, iD_ROLEParameter, iD_ESTADOParameter, iD_COMUNAParameter, iD_EMPRESAParameter, rUTParameter, dVParameter, nOMBREParameter, aPP_PATERParameter, aPP_MATERParameter, dIRECCIONParameter, tELEFONOParameter, eMAILParameter, pASSParameter, lATITUDParameter, lONGITUDParameter, cOD_PAISParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual int SVC_DELETED_USUARIO(Nullable<int> iD_USUARIO)
        {
            var iD_USUARIOParameter = iD_USUARIO.HasValue ?
                new ObjectParameter("ID_USUARIO", iD_USUARIO) :
                new ObjectParameter("ID_USUARIO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SVC_DELETED_USUARIO", iD_USUARIOParameter);
        }
    
        public virtual ObjectResult<Sp_List_Emp_Result> Sp_List_Emp(Nullable<int> var1)
        {
            var var1Parameter = var1.HasValue ?
                new ObjectParameter("Var1", var1) :
                new ObjectParameter("Var1", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_List_Emp_Result>("Sp_List_Emp", var1Parameter);
        }
    
        public virtual int SP_INS_EMPRESA(Nullable<int> iD_COMUNA, Nullable<int> iD_ESTAMENTO, string dESC_EMPRESA)
        {
            var iD_COMUNAParameter = iD_COMUNA.HasValue ?
                new ObjectParameter("ID_COMUNA", iD_COMUNA) :
                new ObjectParameter("ID_COMUNA", typeof(int));
    
            var iD_ESTAMENTOParameter = iD_ESTAMENTO.HasValue ?
                new ObjectParameter("ID_ESTAMENTO", iD_ESTAMENTO) :
                new ObjectParameter("ID_ESTAMENTO", typeof(int));
    
            var dESC_EMPRESAParameter = dESC_EMPRESA != null ?
                new ObjectParameter("DESC_EMPRESA", dESC_EMPRESA) :
                new ObjectParameter("DESC_EMPRESA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_INS_EMPRESA", iD_COMUNAParameter, iD_ESTAMENTOParameter, dESC_EMPRESAParameter);
        }
    
        public virtual int SP_INS_SUCURSAL(Nullable<int> iD_ESTADO, Nullable<int> iD_COMUNA, Nullable<int> iD_EMPRESA, string dIRECCION, string lATITUD, string lONGITUD, string dESCRIPCION)
        {
            var iD_ESTADOParameter = iD_ESTADO.HasValue ?
                new ObjectParameter("ID_ESTADO", iD_ESTADO) :
                new ObjectParameter("ID_ESTADO", typeof(int));
    
            var iD_COMUNAParameter = iD_COMUNA.HasValue ?
                new ObjectParameter("ID_COMUNA", iD_COMUNA) :
                new ObjectParameter("ID_COMUNA", typeof(int));
    
            var iD_EMPRESAParameter = iD_EMPRESA.HasValue ?
                new ObjectParameter("ID_EMPRESA", iD_EMPRESA) :
                new ObjectParameter("ID_EMPRESA", typeof(int));
    
            var dIRECCIONParameter = dIRECCION != null ?
                new ObjectParameter("DIRECCION", dIRECCION) :
                new ObjectParameter("DIRECCION", typeof(string));
    
            var lATITUDParameter = lATITUD != null ?
                new ObjectParameter("LATITUD", lATITUD) :
                new ObjectParameter("LATITUD", typeof(string));
    
            var lONGITUDParameter = lONGITUD != null ?
                new ObjectParameter("LONGITUD", lONGITUD) :
                new ObjectParameter("LONGITUD", typeof(string));
    
            var dESCRIPCIONParameter = dESCRIPCION != null ?
                new ObjectParameter("DESCRIPCION", dESCRIPCION) :
                new ObjectParameter("DESCRIPCION", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_INS_SUCURSAL", iD_ESTADOParameter, iD_COMUNAParameter, iD_EMPRESAParameter, dIRECCIONParameter, lATITUDParameter, lONGITUDParameter, dESCRIPCIONParameter);
        }
    
        public virtual int sp_upd_sucursal(Nullable<int> iD_SUCURSAL, Nullable<int> iD_ESTADO, Nullable<int> iD_COMUNA, Nullable<int> iD_EMPRESA, string dIRECCION, string lATITUD, string lONGITUD, string dESCRIPCION)
        {
            var iD_SUCURSALParameter = iD_SUCURSAL.HasValue ?
                new ObjectParameter("ID_SUCURSAL", iD_SUCURSAL) :
                new ObjectParameter("ID_SUCURSAL", typeof(int));
    
            var iD_ESTADOParameter = iD_ESTADO.HasValue ?
                new ObjectParameter("ID_ESTADO", iD_ESTADO) :
                new ObjectParameter("ID_ESTADO", typeof(int));
    
            var iD_COMUNAParameter = iD_COMUNA.HasValue ?
                new ObjectParameter("ID_COMUNA", iD_COMUNA) :
                new ObjectParameter("ID_COMUNA", typeof(int));
    
            var iD_EMPRESAParameter = iD_EMPRESA.HasValue ?
                new ObjectParameter("ID_EMPRESA", iD_EMPRESA) :
                new ObjectParameter("ID_EMPRESA", typeof(int));
    
            var dIRECCIONParameter = dIRECCION != null ?
                new ObjectParameter("DIRECCION", dIRECCION) :
                new ObjectParameter("DIRECCION", typeof(string));
    
            var lATITUDParameter = lATITUD != null ?
                new ObjectParameter("LATITUD", lATITUD) :
                new ObjectParameter("LATITUD", typeof(string));
    
            var lONGITUDParameter = lONGITUD != null ?
                new ObjectParameter("LONGITUD", lONGITUD) :
                new ObjectParameter("LONGITUD", typeof(string));
    
            var dESCRIPCIONParameter = dESCRIPCION != null ?
                new ObjectParameter("DESCRIPCION", dESCRIPCION) :
                new ObjectParameter("DESCRIPCION", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upd_sucursal", iD_SUCURSALParameter, iD_ESTADOParameter, iD_COMUNAParameter, iD_EMPRESAParameter, dIRECCIONParameter, lATITUDParameter, lONGITUDParameter, dESCRIPCIONParameter);
        }
    
        public virtual int SVC_DELETED_SUCURSAL(Nullable<int> iD_SUCURSAL)
        {
            var iD_SUCURSALParameter = iD_SUCURSAL.HasValue ?
                new ObjectParameter("ID_SUCURSAL", iD_SUCURSAL) :
                new ObjectParameter("ID_SUCURSAL", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SVC_DELETED_SUCURSAL", iD_SUCURSALParameter);
        }
    
        public virtual int sp_upd_estamento(Nullable<int> iD_EMPRESA, Nullable<int> iD_COMUNA, Nullable<int> iD_ESTAMENTO, string dESC_EMPRESA)
        {
            var iD_EMPRESAParameter = iD_EMPRESA.HasValue ?
                new ObjectParameter("ID_EMPRESA", iD_EMPRESA) :
                new ObjectParameter("ID_EMPRESA", typeof(int));
    
            var iD_COMUNAParameter = iD_COMUNA.HasValue ?
                new ObjectParameter("ID_COMUNA", iD_COMUNA) :
                new ObjectParameter("ID_COMUNA", typeof(int));
    
            var iD_ESTAMENTOParameter = iD_ESTAMENTO.HasValue ?
                new ObjectParameter("ID_ESTAMENTO", iD_ESTAMENTO) :
                new ObjectParameter("ID_ESTAMENTO", typeof(int));
    
            var dESC_EMPRESAParameter = dESC_EMPRESA != null ?
                new ObjectParameter("DESC_EMPRESA", dESC_EMPRESA) :
                new ObjectParameter("DESC_EMPRESA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upd_estamento", iD_EMPRESAParameter, iD_COMUNAParameter, iD_ESTAMENTOParameter, dESC_EMPRESAParameter);
        }
    
        public virtual int SVC_DELETED_ESTAMENTO(Nullable<int> iD_EMPRESA)
        {
            var iD_EMPRESAParameter = iD_EMPRESA.HasValue ?
                new ObjectParameter("ID_EMPRESA", iD_EMPRESA) :
                new ObjectParameter("ID_EMPRESA", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SVC_DELETED_ESTAMENTO", iD_EMPRESAParameter);
        }
    
        public virtual int sp_upd_insersion_user(Nullable<int> iD_EMPRESA)
        {
            var iD_EMPRESAParameter = iD_EMPRESA.HasValue ?
                new ObjectParameter("ID_EMPRESA", iD_EMPRESA) :
                new ObjectParameter("ID_EMPRESA", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upd_insersion_user", iD_EMPRESAParameter);
        }
    }
}
