//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AxonAccessMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mae_Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Mae_Usuario()
        {
            this.Ref_UserAccess = new HashSet<Ref_UserAccess>();
        }
    
        public int id_usuario { get; set; }
        public Nullable<int> id_role { get; set; }
        public Nullable<int> id_estado { get; set; }
        public Nullable<int> id_comuna { get; set; }
        public Nullable<int> id_empresa { get; set; }
        public Nullable<int> rut { get; set; }
        public string dv { get; set; }
        public string nombre { get; set; }
        public string app_pater { get; set; }
        public string app_mater { get; set; }
        public string direccion { get; set; }
        public Nullable<int> telefono { get; set; }
        public string mail { get; set; }
        public string pass { get; set; }
        public string latitud { get; set; }
        public string longitud { get; set; }
        public string cargo { get; set; }
    
        public virtual Mae_Comuna Mae_Comuna { get; set; }
        public virtual Mae_Empresa Mae_Empresa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ref_UserAccess> Ref_UserAccess { get; set; }
        public virtual Ref_Estado Ref_Estado { get; set; }
        public virtual Ref_Role Ref_Role { get; set; }
    }
}
