//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AxonAccessMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mae_Sucursal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Mae_Sucursal()
        {
            this.Mae_Puerta = new HashSet<Mae_Puerta>();
        }
    
        public int id_sucursal { get; set; }
        public Nullable<int> id_estado { get; set; }
        public Nullable<int> id_comuna { get; set; }
        public Nullable<int> id_empresa { get; set; }
        public string direccion { get; set; }
        public string latitud { get; set; }
        public string longitud { get; set; }
        public string descripcion { get; set; }
    
        public virtual Mae_Comuna Mae_Comuna { get; set; }
        public virtual Mae_Empresa Mae_Empresa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mae_Puerta> Mae_Puerta { get; set; }
        public virtual Ref_Estado Ref_Estado { get; set; }
    }
}
