//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AxonAccessMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ref_UserAccess
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ref_UserAccess()
        {
            this.Ref_DetalleAcceso = new HashSet<Ref_DetalleAcceso>();
        }
    
        public int id_acceso { get; set; }
        public Nullable<int> id_usuario { get; set; }
        public Nullable<int> id_puerta { get; set; }
        public string desc_puerta { get; set; }
        public Nullable<System.DateTime> fecha_acceso { get; set; }
    
        public virtual Mae_Puerta Mae_Puerta { get; set; }
        public virtual Mae_Usuario Mae_Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ref_DetalleAcceso> Ref_DetalleAcceso { get; set; }
    }
}
