//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AxonAccessMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ref_DetalleAcceso
    {
        public int id_detalle { get; set; }
        public Nullable<int> id_acceso { get; set; }
        public Nullable<System.DateTime> fecha_detalle { get; set; }
        public Nullable<int> conteo_ingreso { get; set; }
        public string desc_detalle { get; set; }
    
        public virtual Ref_UserAccess Ref_UserAccess { get; set; }
    }
}
