//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AxonAccessMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO_AUD
    {
        public int id_registro { get; set; }
        public Nullable<int> id_usuario { get; set; }
        public string nombre { get; set; }
        public string concepto { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
    }
}
